apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-elasticsearch
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.esUsername | b64enc | quote }}
  password: {{ .Values.esPassword | b64enc | quote }}

