---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: wo84xel
  name: wo84xel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wo84xel-binding
  namespace: wo84xel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wo84xel
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:maximilian.ernst@uni-jena.de
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wo84xel
  namespace: wo84xel
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
